import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import './components/styles/main_page.css'
import HeaderComponent from "./components/Header";
import FooterComponent from "./components/Footer";
import StyledComponentsRegistry from "./components/styled-com/RenderStylesComponent";
const inter = Poppins({
  subsets: ['latin', 'latin-ext'],
  weight: ["100", '200', '300', '400', '500', '600', '700']
});

export const metadata: Metadata = {
  title: "FASHION",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <HeaderComponent />
          {children}
          <FooterComponent />
        </StyledComponentsRegistry>

      </body>
    </html>
  );
}
